# Generated by Django 5.1.4 on 2024-12-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokergame",
            name="end time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="pokergame",
            name="start time",
            field=models.DateTimeField(null=True),
        ),
    ]
