# Generated by Django 5.1.4 on 2025-01-06 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_pokergame_end_time_alter_pokergame_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeringame",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pokergame",
            name="start time",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2025, 1, 6, 20, 21, 39, 424610, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
