# Generated by Django 5.1.4 on 2025-01-20 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_playeringame_last_active_alter_pokergame_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playeringame",
            name="chips",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
