# Generated by Django 5.1.4 on 2025-02-02 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_playeringame_chips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeringame',
            name='chips',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Chips must be a positive value')]),
        ),
        migrations.AlterField(
            model_name='pokergame',
            name='max_players',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(9, 'Maximum players must be less than 9'), django.core.validators.MinValueValidator(2, 'Must have at least 2 players')]),
        ),
    ]
