# Generated by Django 5.1.4 on 2024-12-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lobby_name", models.CharField(max_length=20)),
                ("start_date", models.DateField(verbose_name="date started")),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
