# Generated by Django 5.1.4 on 2025-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0002_alter_lobby_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="start_date",
            field=models.DateTimeField(auto_now=True, verbose_name="date started"),
        ),
    ]
