# Generated by Django 5.1.4 on 2025-01-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0003_alter_lobby_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
